"""Playwright-based WAF block page analyzer.

Renders WAF block pages in a real browser to extract full page content
(JS-rendered DOM, custom error pages, WAF brand identifiers, JS challenges).
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger("bypassevo.browser")


@dataclass
class BlockPageResult:
    """Result from analyzing a WAF block page in a browser."""
    url: str
    status_code: int = 0
    page_title: str = ""
    rendered_text: str = ""         # Full visible text after JS rendering
    html_snippet: str = ""          # Key HTML snippet (first 2000 chars)
    waf_indicators: list[str] = field(default_factory=list)  # Detected WAF markers
    js_challenge: bool = False      # Whether a JS challenge was detected
    challenge_type: str = ""        # "cloudflare_turnstile", "recaptcha", "hcaptcha", etc.
    custom_block_page: bool = False # Whether this is a custom block page (not generic 403)
    error_message: str = ""
    screenshot_path: str = ""       # Path to screenshot if saved


# Known WAF block page signatures
_WAF_SIGNATURES = {
    "cloudflare": [
        r"cloudflare", r"cf-ray", r"checking your browser",
        r"just a moment", r"ddos protection by cloudflare",
        r"cf-browser-verification", r"turnstile",
    ],
    "akamai": [
        r"akamai", r"reference.*#\d+\.\w+", r"access denied.*akamai",
        r"the requested url was rejected",
    ],
    "imperva": [
        r"imperva", r"incapsula", r"incap_ses",
        r"request unsuccessful\.incapsula",
    ],
    "sucuri": [
        r"sucuri", r"access denied.*sucuri",
        r"blocked by sucuri", r"website firewall by sucuri",
    ],
    "wordfence": [
        r"wordfence", r"generated by wordfence",
        r"your access to this site has been limited",
    ],
    "modsecurity": [
        r"mod_security", r"modsecurity", r"not acceptable",
        r"an error occurred", r"403 forbidden.*mod",
    ],
    "barracuda": [
        r"barracuda", r"you have been blocked",
    ],
    "f5_bigip": [
        r"f5 networks", r"bigip", r"the url is currently blocked",
    ],
    "fortiweb": [
        r"fortiweb", r"fortinet", r"web application firewall",
    ],
    "aws_waf": [
        r"aws", r"access denied.*aws",
        r"the request could not be satisfied",
    ],
    "generic_waf": [
        r"blocked by web application firewall",
        r"your request has been blocked",
        r"security violation detected",
        r"forbidden.*you don\'t have permission",
        r"attack detected",
    ],
}

# JS challenge patterns
_JS_CHALLENGE_PATTERNS = {
    "cloudflare_turnstile": [r"turnstile", r"cf-challenge", r"cf_chl"],
    "cloudflare_js_challenge": [r"checking your browser", r"just a moment.*cloudflare"],
    "recaptcha": [r"recaptcha", r"g-recaptcha"],
    "hcaptcha": [r"hcaptcha", r"h-captcha"],
    "generic_challenge": [r"please wait.*loading", r"enable javascript", r"browser.*verification"],
}


def _detect_waf_from_page(text: str, headers: dict = None) -> list[str]:
    """Detect WAF type from rendered page content and headers."""
    text_lower = text.lower()
    headers_str = " ".join(f"{k}: {v}" for k, v in (headers or {}).items()).lower()
    combined = f"{text_lower} {headers_str}"

    found = []
    for waf_name, patterns in _WAF_SIGNATURES.items():
        for pattern in patterns:
            if re.search(pattern, combined):
                found.append(waf_name)
                break
    return found


def _detect_js_challenge(text: str) -> tuple[bool, str]:
    """Detect if the page has a JS challenge."""
    text_lower = text.lower()
    for challenge_type, patterns in _JS_CHALLENGE_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, text_lower):
                return True, challenge_type
    return False, ""


def _is_custom_block_page(text: str) -> bool:
    """Detect if this is a custom branded block page (not generic 403)."""
    indicators = [
        # Has a styled error message
        r"<style", r"font-family", r"background-color",
        # Has a custom message
        r"blocked", r"denied", r"security", r"violation",
        # Has a logo or brand
        r"<img.*logo", r"waf", r"firewall",
    ]
    text_lower = text.lower()
    matches = sum(1 for p in indicators if re.search(p, text_lower))
    return matches >= 2


class BrowserAnalyzer:
    """Analyze WAF block pages using a headless browser."""

    def __init__(self, timeout: int = 15, screenshot_dir: str = ""):
        self.timeout = timeout * 1000  # Playwright uses ms
        self.screenshot_dir = screenshot_dir
        self._available: Optional[bool] = None

    def _check_available(self) -> bool:
        if self._available is None:
            try:
                from playwright.sync_api import sync_playwright
                self._available = True
            except ImportError:
                logger.warning("playwright not installed: pip install playwright && playwright install chromium")
                self._available = False
        return self._available

    def analyze_block_page(
        self,
        url: str,
        cookies: dict = None,
        headers: dict = None,
        take_screenshot: bool = False,
    ) -> BlockPageResult:
        """Navigate to a URL in a headless browser and analyze the block page.

        Args:
            url: The full URL (with payload in query string if applicable)
            cookies: Cookie dict to set (e.g., PHPSESSID, security level)
            headers: Extra HTTP headers
            take_screenshot: Whether to save a screenshot

        Returns:
            BlockPageResult with rendered content and analysis
        """
        if not self._check_available():
            return BlockPageResult(url=url, error_message="playwright not installed")

        result = BlockPageResult(url=url)

        try:
            from playwright.sync_api import sync_playwright

            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                context = browser.new_context(
                    ignore_https_errors=True,
                    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                )

                # Set cookies
                if cookies:
                    cookie_list = []
                    for name, value in cookies.items():
                        cookie_list.append({
                            "name": name,
                            "value": value,
                            "domain": url.split("//")[-1].split("/")[0].split(":")[0],
                            "path": "/",
                        })
                    context.add_cookies(cookie_list)

                page = context.new_page()

                # Set extra headers
                if headers:
                    page.set_extra_http_headers(headers)

                # Navigate
                response = page.goto(url, wait_until="networkidle", timeout=self.timeout)

                if response:
                    result.status_code = response.status

                # Wait a bit for JS challenges to load
                page.wait_for_timeout(2000)

                # Extract content
                result.page_title = page.title()
                result.rendered_text = page.inner_text("body")[:3000]
                result.html_snippet = page.content()[:5000]

                # Detect WAF indicators
                resp_headers = {}
                if response:
                    resp_headers = response.headers
                result.waf_indicators = _detect_waf_from_page(result.rendered_text, resp_headers)

                # Detect JS challenges
                result.js_challenge, result.challenge_type = _detect_js_challenge(result.html_snippet)

                # Detect custom block page
                result.custom_block_page = _is_custom_block_page(result.html_snippet)

                # Take screenshot if requested
                if take_screenshot and self.screenshot_dir:
                    try:
                        import os
                        os.makedirs(self.screenshot_dir, exist_ok=True)
                        path = os.path.join(self.screenshot_dir, f"block_{hash(url) % 100000}.png")
                        page.screenshot(path=path, full_page=True)
                        result.screenshot_path = path
                    except Exception as e:
                        logger.warning(f"Screenshot failed: {e}")

                browser.close()

        except Exception as e:
            result.error_message = str(e)[:200]
            logger.error(f"[BROWSER] Analysis failed: {e}")

        return result


def format_block_page_for_prompt(result: BlockPageResult) -> str:
    """Format block page analysis for LLM prompt injection."""
    if result.error_message:
        return f"[Browser Analysis: unavailable — {result.error_message}]"

    lines = ["[Browser-Rendered Block Page Analysis]"]
    lines.append(f"URL: {result.url[:100]}")
    lines.append(f"Status: {result.status_code}")
    lines.append(f"Title: {result.page_title[:100]}")

    if result.waf_indicators:
        lines.append(f"WAF detected in page: {', '.join(result.waf_indicators)}")

    if result.js_challenge:
        lines.append(f"JS Challenge detected: {result.challenge_type}")

    if result.custom_block_page:
        lines.append("Page type: Custom branded block page (not generic 403)")

    if result.rendered_text:
        # Extract the most relevant lines (skip boilerplate)
        text = result.rendered_text[:1500]
        lines.append(f"Rendered content:\n{text}")

    return "\n".join(lines)
