"""
BypassEvo Report Generator — Markdown reports for bypass discoveries and exploit results.
"""

import json
import time
from datetime import datetime


def generate_report(
    waf_result: dict,
    bypass_techniques: list,
    exploit_result: dict,
    history: list,
    ga_stats: dict,
    vuln_type: str,
    target_url: str,
    endpoint: str,
) -> str:
    """Generate a Markdown report of the full attack session."""

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    waf_name = waf_result.get("waf_name", "none")
    bypass_success = bool(bypass_techniques)

    lines = [
        f"# BypassEvo Attack Report",
        f"",
        f"**Generated:** {now}",
        f"**Target:** `{target_url}{endpoint}`",
        f"**Vulnerability Type:** {vuln_type.upper()}",
        f"**WAF Detected:** {waf_name} (confidence={waf_result.get('confidence', 0):.2f})",
        f"",
        f"---",
        f"",
        f"## 1. WAF Detection",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| WAF Name | {waf_name} |",
        f"| Confidence | {waf_result.get('confidence', 0):.2f} |",
        f"| Indicators | {', '.join(waf_result.get('indicators', [])[:5])} |",
        f"",
    ]

    # Bypass techniques
    if bypass_techniques:
        lines += [
            f"## 2. Discovered Bypass Techniques",
            f"",
            f"**{len(bypass_techniques)} bypass technique(s) discovered:**",
            f"",
        ]
        for i, tech in enumerate(bypass_techniques, 1):
            lines += [
                f"### Bypass #{i}",
                f"",
                f"- **Technique:** {tech.get('technique', 'N/A')}",
                f"- **Payload:** `{tech.get('payload', 'N/A')}`",
                f"- **WAF Rule Bypassed:** {tech.get('rule_type', 'N/A')}",
                f"- **Trigger Pattern:** `{tech.get('trigger_pattern', 'N/A')}`",
                f"- **Reasoning:** {tech.get('reasoning', 'N/A')}",
                f"",
            ]
    else:
        lines += [
            f"## 2. WAF Bypass",
            f"",
            f"No bypass techniques were discovered. The WAF may be too restrictive or the target may not be behind a WAF.",
            f"",
        ]

    # Exploit results
    lines += [f"## 3. Exploit Results", f""]

    if exploit_result and exploit_result.get("success"):
        lines += [
            f"**VULNERABILITY CONFIRMED**",
            f"",
            f"- **Payload:** `{exploit_result.get('payload', 'N/A')}`",
            f"- **Evidence:** {exploit_result.get('evidence', 'N/A')}",
            f"- **Confidence:** {exploit_result.get('confidence', 0):.2f}",
            f"- **Response Code:** {exploit_result.get('response_code', 'N/A')}",
            f"",
        ]
    elif exploit_result:
        lines += [
            f"Exploit attempted but vulnerability not confirmed.",
            f"",
            f"- **Last Payload:** `{exploit_result.get('payload', 'N/A')}`",
            f"- **Evidence:** {exploit_result.get('evidence', 'None')}",
            f"",
        ]
    else:
        lines += [f"No exploit attempts were made (WAF bypass phase did not complete).", f""]

    # GA Statistics
    if ga_stats:
        lines += [
            f"## 4. Genetic Algorithm Statistics",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Generations | {ga_stats.get('generation', 0)} |",
            f"| Best Fitness | {ga_stats.get('best_fitness', 0):.3f} |",
            f"| Avg Fitness | {ga_stats.get('avg_fitness', 0):.3f} |",
            f"| Mutation Rate | {ga_stats.get('mutation_rate', 0):.3f} |",
            f"| Population Size | {ga_stats.get('population_size', 0)} |",
            f"",
        ]

    # Attack history summary
    if history:
        successes = [h for h in history if h.get("result") == "success"]
        failures = [h for h in history if h.get("result") == "failure"]
        blocks = [h for h in history if h.get("result") == "blocked"]

        lines += [
            f"## 5. Attack History Summary",
            f"",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total Attempts | {len(history)} |",
            f"| Successes | {len(successes)} |",
            f"| Failures | {len(failures)} |",
            f"| WAF Blocks | {len(blocks)} |",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"*Report generated by BypassEvo v2.0 — AI-Driven WAF Bypass Research & Exploit Framework*",
    ]

    return "\n".join(lines)


def save_report(report: str, path: str = "./reports") -> str:
    """Save report to file and return the path."""
    import os
    os.makedirs(path, exist_ok=True)
    filename = f"bypassevo_report_{int(time.time())}.md"
    filepath = os.path.join(path, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)
    return filepath
