"""
BypassEvo WAF Fingerprinting & Adaptive Bypass

Detects common WAFs by probing the target with known fingerprints and
provides bypass strategy sets tailored to each WAF.
"""

import re
import requests
from dataclasses import dataclass, field


@dataclass
class WAFResult:
    detected: bool = False
    waf_name: str = "none"
    confidence: float = 0.0
    indicators: list = field(default_factory=list)
    bypass_strategies: list = field(default_factory=list)


# ── WAF Fingerprints ───────────────────────────────────────────────────

WAF_FINGERPRINTS = {
    "cloudflare": {
        "headers": {
            "server": r"cloudflare",
            "cf-ray": r".+",
            "cf-cache-status": r".+",
        },
        "body_patterns": [
            r"cloudflare.*ray id",
            r"attention required.*cloudflare",
            r"cf-browser-verification",
        ],
        "block_status": [403, 503],
        "probe_keywords": ["<script>", "union select", "../"],
    },
    "aws_waf": {
        "headers": {
            "x-amzn-requestid": r".+",
            "x-amz-cf-id": r".+",
            "server": r"CloudFront",
        },
        "body_patterns": [
            r"<html><head>.*403.*forbidden",
            r"access denied.*aws",
        ],
        "block_status": [403],
        "probe_keywords": ["../", "<script>"],
    },
    "modsecurity": {
        "headers": {
            "server": r"Apache",
        },
        "body_patterns": [
            r"mod_security",
            r"modsecurity",
            r"this error was generated by mod_security",
            r"not acceptable.*mod_security",
        ],
        "block_status": [403, 406, 501],
        "probe_keywords": ["' or 1=1", "<script>", "../"],
    },
    "nginx_waf": {
        "headers": {
            "server": r"nginx",
        },
        "body_patterns": [
            r"nginx.*forbidden",
            r"request blocked.*nginx",
        ],
        "block_status": [403, 406],
        "probe_keywords": ["union select", "<script>"],
    },
    "akamai": {
        "headers": {
            "x-akamai": r".+",
            "server": r"AkamaiGHost",
        },
        "body_patterns": [
            r"access denied.*akamai",
            r"reference.*akamai",
        ],
        "block_status": [403],
        "probe_keywords": ["<script>", "union select"],
    },
    "sucuri": {
        "headers": {
            "server": r"sucuri",
            "x-sucuri-id": r".+",
        },
        "body_patterns": [
            r"sucuri.*blocked",
            r"access denied.*sucuri",
        ],
        "block_status": [403],
        "probe_keywords": ["union select", "<script>"],
    },
    "wordfence": {
        "body_patterns": [
            r"wordfence",
            r"generated by wordfence",
            r"blocked by wordfence",
        ],
        "block_status": [403, 503],
        "probe_keywords": ["union select", "<script>"],
    },
    "imperva": {
        "headers": {
            "x-iinfo": r".+",
        },
        "body_patterns": [
            r"imperva",
            r"incapsula",
            r"blocked.*imperva",
        ],
        "block_status": [403],
        "probe_keywords": ["<script>", "union select"],
    },
}

# ── Bypass Strategy Sets ───────────────────────────────────────────────

BYPASS_STRATEGIES = {
    "cloudflare": [
        "comment_injection",        # UN/**/ION SEL/**/ECT
        "case_variation",           # UnIoN sElEcT
        "double_encoding",          # %2527 → %27 → '
        "unicode_normalization",    # Full-width chars
        "json_content_type",        # application/json bypass
        "chunked_transfer",         # Chunked encoding
    ],
    "aws_waf": [
        "json_content_type",
        "case_variation",
        "comment_injection",
        "parameter_pollution",      # HPP
        "http_method_switch",       # GET → POST → PUT
    ],
    "modsecurity": [
        "comment_injection",
        "case_variation",
        "newline_injection",        # %0a in payload
        "null_byte",               # %00
        "multi_part_bypass",       # multipart/form-data
        "chunked_transfer",
    ],
    "nginx_waf": [
        "path_traversal_encode",    # ..%2f
        "case_variation",
        "newline_injection",
        "unicode_bypass",
    ],
    "akamai": [
        "chunked_transfer",
        "case_variation",
        "comment_injection",
        "json_content_type",
    ],
    "sucuri": [
        "case_variation",
        "comment_injection",
        "unicode_bypass",
        "newline_injection",
    ],
    "wordfence": [
        "case_variation",
        "comment_injection",
        "double_encoding",
        "null_byte",
    ],
    "imperva": [
        "json_content_type",
        "case_variation",
        "comment_injection",
        "chunked_transfer",
        "http_method_switch",
    ],
    "none": [],  # No WAF detected, standard mutation
    "unknown": [  # WAF detected but not identified — use ALL families
        "comment_injection",
        "case_variation",
        "double_encoding",
        "unicode_normalization",
        "json_content_type",
        "chunked_transfer",
        "newline_injection",
        "null_byte",
        "multi_part_bypass",
        "parameter_pollution",
        "http_method_switch",
        "encoding_overload",
        "parser_differential",
    ],
}


class WAFDetector:
    """Detect WAF and provide bypass strategies."""

    def __init__(self, timeout: int = 8, php_sessid: str = ""):
        self.timeout = timeout
        self.session = requests.Session()
        from tools.scanner import BROWSER_HEADERS
        self.session.headers.update(BROWSER_HEADERS)
        if php_sessid:
            self.session.cookies.set("PHPSESSID", php_sessid, path="/")
            self.session.cookies.set("security", "low", path="/")

    def detect(self, base_url: str, path: str = "/") -> WAFResult:
        """Probe the target to identify any WAF.

        Sends benign + mildly malicious requests and analyzes responses
        for WAF fingerprints.
        """
        # Normalize base_url to scheme+host only, then join with path
        from urllib.parse import urlparse
        parsed = urlparse(base_url)
        norm_base = f"{parsed.scheme}://{parsed.netloc}".rstrip("/")
        path_clean = path.lstrip("/") if path.startswith("/") else path
        url = f"{norm_base}/{path_clean}"

        # Step 1: Baseline request
        try:
            baseline = self.session.get(url, timeout=self.timeout)
        except Exception as e:
            return WAFResult(detected=False, waf_name="unreachable", indicators=[str(e)])

        baseline_headers = {k.lower(): v for k, v in baseline.headers.items()}
        baseline_body = baseline.text[:3000]

        # Step 2: Probe with mildly suspicious payloads
        probes = [
            "' OR 1=1--",
            "<script>alert(1)</script>",
            "../../../etc/passwd",
            "UNION SELECT NULL--",
        ]

        probe_results = []
        for probe in probes:
            try:
                resp = self.session.get(
                    url, params={"q": probe}, timeout=self.timeout
                )
                probe_results.append({
                    "status": resp.status_code,
                    "headers": {k.lower(): v for k, v in resp.headers.items()},
                    "body": resp.text[:2000],
                })
            except Exception:
                continue

        # Step 3: Match against fingerprints
        best_match = WAFResult(detected=False, waf_name="none")

        for waf_name, fingerprint in WAF_FINGERPRINTS.items():
            score = 0.0
            indicators = []

            # Check headers from all probe responses
            for pr in probe_results:
                for header_name, header_pattern in fingerprint.get("headers", {}).items():
                    header_val = pr["headers"].get(header_name, "")
                    if header_val and re.search(header_pattern, header_val, re.IGNORECASE):
                        score += 0.3
                        indicators.append(f"header:{header_name}={header_val[:30]}")

                # Check body patterns
                for body_pattern in fingerprint.get("body_patterns", []):
                    if re.search(body_pattern, pr["body"], re.IGNORECASE):
                        score += 0.4
                        indicators.append(f"body_match:{body_pattern[:30]}")

                # Check block status codes
                if pr["status"] in fingerprint.get("block_status", []):
                    score += 0.2
                    indicators.append(f"block_status:{pr['status']}")

            # Also check baseline headers
            for header_name, header_pattern in fingerprint.get("headers", {}).items():
                header_val = baseline_headers.get(header_name, "")
                if header_val and re.search(header_pattern, header_val, re.IGNORECASE):
                    score += 0.2
                    indicators.append(f"baseline_header:{header_name}")

            if score > best_match.confidence:
                best_match = WAFResult(
                    detected=True,
                    waf_name=waf_name,
                    confidence=min(score, 1.0),
                    indicators=list(set(indicators)),
                    bypass_strategies=BYPASS_STRATEGIES.get(waf_name, []),
                )

        # Threshold: need at least 0.3 confidence to declare WAF detected
        if best_match.confidence < 0.3:
            best_match = WAFResult(detected=False, waf_name="none")

        # If WAF detected but no specific match, mark as "unknown"
        if best_match.detected and best_match.waf_name == "none":
            best_match.waf_name = "unknown"
            best_match.bypass_strategies = BYPASS_STRATEGIES.get("unknown", [])

        return best_match

    def get_bypass_families_tried(self, bypass_history: list[dict]) -> list[str]:
        """Analyze bypass history to determine which families have been tried.

        Returns list of family names that have been attempted.
        """
        families_tried = set()
        for entry in bypass_history:
            technique = entry.get("technique", "").lower()
            if "comment" in technique:
                families_tried.add("comment_injection")
            if "case" in technique:
                families_tried.add("case_variation")
            if "encod" in technique or "double" in technique:
                families_tried.add("encoding_chain")
            if "unicode" in technique or "fullwidth" in technique:
                families_tried.add("unicode")
            if "json" in technique:
                families_tried.add("json_content_type")
            if "chunk" in technique:
                families_tried.add("chunked_transfer")
            if "newline" in technique or "%0a" in technique:
                families_tried.add("newline_injection")
            if "null" in technique or "%00" in technique:
                families_tried.add("null_byte")
            if "multipart" in technique:
                families_tried.add("multi_part_bypass")
            if "pollution" in technique or "hpp" in technique:
                families_tried.add("parameter_pollution")
            if "method" in technique or "put" in technique:
                families_tried.add("http_method_switch")
        return list(families_tried)

    def get_bypass_weights(self, waf_name: str) -> dict:
        """Get mutation operator weights adjusted for the detected WAF.

        Returns a dict mapping mutation strategy names to weight multipliers.
        Higher weight = more likely to be selected during GA mutation.
        """
        base_weights = {
            "comment_injection": 1.0,
            "case_variation": 1.0,
            "encoding": 1.0,
            "space_bypass": 1.0,
            "quote_bypass": 1.0,
            "newline_injection": 1.0,
            "unicode_bypass": 1.0,
            "json_content_type": 1.0,
            "chunked_transfer": 1.0,
            "double_encoding": 1.0,
            "null_byte": 1.0,
            "parameter_pollution": 1.0,
        }

        strategies = BYPASS_STRATEGIES.get(waf_name, [])
        for strategy in strategies:
            if strategy in base_weights:
                base_weights[strategy] = 2.5  # Boost WAF-specific strategies

        return base_weights
